[package]
name = "kafka_writer_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = "0.39.0"
tokio = { version = "1.48", features = ["full"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
